name: tests
on:
- push
- workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
    - run: npm install
    - run: npm run build
    - run: npm test
    - uses: denoland/setup-deno@v2
    - run: npm run test-lint